### ISSUE TITLE
build: package to handle io with cloud bucket

### ISSUE THREAD

**Issue by akouete-kpakpo** [akouete-kpakpo/cloud_io#2]
## Tasks

- [x] build the package cloud_io
- [x] add a setup via submodule 
- [x] make an end-to-end test: a test on a tuto notebook is enough
- [x] run the tests
   - [x] in local
   - [x] automatize the running with a recipe -> build a Makefile
   - [x] in remote: make a ci 
- [ ] release the package on PyPI
